import React from 'react';
import { View } from 'react-native';
import { Scene, Actions, Router, Stack } from 'react-native-router-flux';
import { connect } from 'react-redux';
import styles from './styles';
import { AppRoutes } from './routes';

/**
 * DO NOT edit this file if you want to add new Scene
 * If you want to add a new one, take a look at ./routes.js
 */

export const RootScene = (
  <Stack key="root">
    {Object.keys(AppRoutes).map(key => {
      const { name, scene, initial } = AppRoutes[key];
      return (
        <Scene key={key} title={name} component={scene} initial={initial} />
      );
    })}
  </Stack>
);

const navigator = Actions.create(RootScene);
const ReduxRouter = connect(state => ({ state: state['navigation'] }))(Router);

const AppNavigation = () =>
  <View style={[styles.container, styles.statusBar]}>
    <ReduxRouter navigator={navigator} />
  </View>;

export default AppNavigation;
