import React from 'react';
import { View } from 'react-native';
import { Router, Stack, Scene } from 'react-native-router-flux';
import styles from './styles';
import { AppRoutes } from './routes';

/**
 * DO NOT edit this file if you want to add new Scene
 * If you want to add a new one, take a look at ./routes.js
 */

const AppNavigation = () => (
  <View style={[styles.container, styles.statusBar]}>
    <Router>
      <Stack key="root">
        {Object.keys(AppRoutes).map(key => {
          const { name, scene, initial } = AppRoutes[key];
          return (
            <Scene key={key} title={name} component={scene} initial={initial} />
          );
        })}
      </Stack>
    </Router>
  </View>
);

export default AppNavigation;
